CREATE DATABASE IF NOT EXISTS cm_order_management CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE cm_order_management;

CREATE TABLE IF NOT EXISTS customers (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  customer_code VARCHAR(50) NULL,
  customer_name VARCHAR(255) NOT NULL,
  customer_id_external VARCHAR(100) NULL,
  marketplace_customer_id VARCHAR(100) NULL,
  phone VARCHAR(50) NULL,
  phone_alt VARCHAR(50) NULL,
  email VARCHAR(255) NULL,
  source_type VARCHAR(50) DEFAULT 'MANUAL',
  source_account_id BIGINT NULL,
  source_account_code VARCHAR(100) NULL,
  source_account_name VARCHAR(255) NULL,
  shipping_full_name VARCHAR(255) NULL,
  shipping_phone VARCHAR(50) NULL,
  shipping_address_line1 VARCHAR(255) NULL,
  shipping_address_line2 VARCHAR(255) NULL,
  shipping_city VARCHAR(120) NULL,
  shipping_district VARCHAR(120) NULL,
  shipping_province VARCHAR(120) NULL,
  shipping_postal_code VARCHAR(50) NULL,
  shipping_country VARCHAR(120) DEFAULT 'Sri Lanka',
  billing_full_name VARCHAR(255) NULL,
  billing_phone VARCHAR(50) NULL,
  billing_address_line1 VARCHAR(255) NULL,
  billing_address_line2 VARCHAR(255) NULL,
  billing_city VARCHAR(120) NULL,
  billing_district VARCHAR(120) NULL,
  billing_province VARCHAR(120) NULL,
  billing_postal_code VARCHAR(50) NULL,
  billing_country VARCHAR(120) DEFAULT 'Sri Lanka',
  customer_note TEXT NULL,
  internal_note TEXT NULL,
  total_orders INT NOT NULL DEFAULT 0,
  total_spent DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  last_order_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_customers_phone (phone),
  KEY idx_customers_email (email),
  KEY idx_customers_marketplace_customer_id (marketplace_customer_id)
);

CREATE TABLE IF NOT EXISTS orders (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  order_no VARCHAR(100) NOT NULL,
  customer_id BIGINT UNSIGNED NULL,
  source_type VARCHAR(50) DEFAULT 'MANUAL_OTHER',
  source_label VARCHAR(150) NULL,
  account_id BIGINT NULL,
  account_code VARCHAR(100) NULL,
  account_name VARCHAR(255) NULL,
  customer_order_ref VARCHAR(150) NULL,
  order_status VARCHAR(80) DEFAULT 'Pending',
  payment_status VARCHAR(80) DEFAULT 'Unpaid',
  payment_method VARCHAR(80) NULL,
  order_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  item_total DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  discount_total DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  shipping_fee DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  cod_fee DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  tax_total DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  grand_total DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  currency VARCHAR(10) DEFAULT 'LKR',
  customer_note TEXT NULL,
  internal_note TEXT NULL,
  raw_payload JSON NULL,
  shipped_at DATETIME NULL,
  created_by BIGINT NULL,
  updated_by BIGINT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_orders_order_no (order_no),
  KEY idx_orders_customer_id (customer_id),
  KEY idx_orders_order_date (order_date),
  KEY idx_orders_status (order_status)
);

CREATE TABLE IF NOT EXISTS order_items (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  order_id BIGINT UNSIGNED NOT NULL,
  product_id BIGINT NULL,
  variant_id BIGINT NULL,
  local_sku VARCHAR(150) NULL,
  sku VARCHAR(150) NULL,
  product_title VARCHAR(500) NULL,
  variation_name VARCHAR(255) NULL,
  product_image_url TEXT NULL,
  qty INT NOT NULL DEFAULT 1,
  unit_price DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  discount_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  line_total DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  item_status VARCHAR(80) DEFAULT 'Pending',
  stock_deducted TINYINT(1) NOT NULL DEFAULT 0,
  stock_deducted_at DATETIME NULL,
  stock_movement_id BIGINT NULL,
  raw_payload JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_order_items_order_id (order_id),
  KEY idx_order_items_sku (sku),
  KEY idx_order_items_local_sku (local_sku)
);

CREATE TABLE IF NOT EXISTS daraz_orders (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  account_id BIGINT NULL,
  account_code VARCHAR(100) NULL,
  account_name VARCHAR(255) NULL,
  daraz_order_id VARCHAR(100) NOT NULL,
  order_number VARCHAR(100) NULL,
  order_status VARCHAR(100) NULL,
  payment_status VARCHAR(100) NULL,
  payment_method VARCHAR(100) NULL,
  order_date DATETIME NULL,
  created_time DATETIME NULL,
  updated_time DATETIME NULL,
  promised_shipping_time DATETIME NULL,
  buyer_name VARCHAR(255) NULL,
  buyer_phone VARCHAR(80) NULL,
  shipping_name VARCHAR(255) NULL,
  shipping_phone VARCHAR(80) NULL,
  shipping_address TEXT NULL,
  shipping_city VARCHAR(120) NULL,
  shipping_region VARCHAR(120) NULL,
  item_total DECIMAL(12,2) DEFAULT 0.00,
  discount_total DECIMAL(12,2) DEFAULT 0.00,
  shipping_fee DECIMAL(12,2) DEFAULT 0.00,
  voucher_total DECIMAL(12,2) DEFAULT 0.00,
  grand_total DECIMAL(12,2) DEFAULT 0.00,
  currency VARCHAR(10) DEFAULT 'LKR',
  customer_id BIGINT NULL,
  raw_payload JSON NULL,
  synced_at DATETIME NULL,
  last_synced_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_daraz_order_account (account_id, daraz_order_id),
  KEY idx_daraz_orders_status (order_status),
  KEY idx_daraz_orders_order_date (order_date)
);

CREATE TABLE IF NOT EXISTS daraz_order_items (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  daraz_order_id BIGINT UNSIGNED NOT NULL,
  daraz_order_item_id VARCHAR(100) NULL,
  marketplace_sku VARCHAR(150) NULL,
  seller_sku VARCHAR(150) NULL,
  local_sku VARCHAR(150) NULL,
  product_title VARCHAR(500) NULL,
  variation_name VARCHAR(255) NULL,
  product_image_url TEXT NULL,
  qty INT DEFAULT 1,
  unit_price DECIMAL(12,2) DEFAULT 0.00,
  discount_amount DECIMAL(12,2) DEFAULT 0.00,
  paid_price DECIMAL(12,2) DEFAULT 0.00,
  line_total DECIMAL(12,2) DEFAULT 0.00,
  item_status VARCHAR(100) NULL,
  tracking_code VARCHAR(150) NULL,
  package_id VARCHAR(150) NULL,
  stock_deducted TINYINT(1) DEFAULT 0,
  stock_deducted_at DATETIME NULL,
  stock_movement_id BIGINT NULL,
  raw_payload JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_daraz_item_order_item (daraz_order_id, daraz_order_item_id),
  KEY idx_daraz_items_order_id (daraz_order_id),
  KEY idx_daraz_items_sku (seller_sku),
  KEY idx_daraz_items_local_sku (local_sku)
);

CREATE TABLE IF NOT EXISTS woo_orders (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  account_id BIGINT NULL,
  account_code VARCHAR(100) NULL,
  account_name VARCHAR(255) NULL,
  woo_order_id VARCHAR(100) NOT NULL,
  order_number VARCHAR(100) NULL,
  order_status VARCHAR(100) NULL,
  payment_status VARCHAR(100) NULL,
  payment_method VARCHAR(100) NULL,
  order_date DATETIME NULL,
  created_time DATETIME NULL,
  updated_time DATETIME NULL,
  promised_shipping_time DATETIME NULL,
  buyer_name VARCHAR(255) NULL,
  buyer_phone VARCHAR(80) NULL,
  buyer_email VARCHAR(255) NULL,
  shipping_name VARCHAR(255) NULL,
  shipping_phone VARCHAR(80) NULL,
  shipping_address TEXT NULL,
  shipping_city VARCHAR(120) NULL,
  shipping_region VARCHAR(120) NULL,
  item_total DECIMAL(12,2) DEFAULT 0.00,
  discount_total DECIMAL(12,2) DEFAULT 0.00,
  shipping_fee DECIMAL(12,2) DEFAULT 0.00,
  tax_total DECIMAL(12,2) DEFAULT 0.00,
  grand_total DECIMAL(12,2) DEFAULT 0.00,
  currency VARCHAR(10) DEFAULT 'LKR',
  customer_id BIGINT NULL,
  raw_payload JSON NULL,
  synced_at DATETIME NULL,
  last_synced_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_woo_order_account (account_id, woo_order_id),
  KEY idx_woo_orders_status (order_status),
  KEY idx_woo_orders_order_date (order_date)
);

CREATE TABLE IF NOT EXISTS woo_order_items (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  woo_order_id BIGINT UNSIGNED NOT NULL,
  woo_order_item_id VARCHAR(100) NULL,
  marketplace_sku VARCHAR(150) NULL,
  sku VARCHAR(150) NULL,
  local_sku VARCHAR(150) NULL,
  product_title VARCHAR(500) NULL,
  variation_name VARCHAR(255) NULL,
  product_image_url TEXT NULL,
  qty INT DEFAULT 1,
  unit_price DECIMAL(12,2) DEFAULT 0.00,
  discount_amount DECIMAL(12,2) DEFAULT 0.00,
  line_total DECIMAL(12,2) DEFAULT 0.00,
  item_status VARCHAR(100) NULL,
  stock_deducted TINYINT(1) DEFAULT 0,
  stock_deducted_at DATETIME NULL,
  stock_movement_id BIGINT NULL,
  raw_payload JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_woo_item_order_item (woo_order_id, woo_line_item_id),
  KEY idx_woo_items_order_id (woo_order_id),
  KEY idx_woo_items_sku (sku),
  KEY idx_woo_items_local_sku (local_sku)
);

CREATE TABLE IF NOT EXISTS trans_express_waybills (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  source_type VARCHAR(50) NOT NULL,
  source_order_id BIGINT NOT NULL,
  waybill_id VARCHAR(150) NULL,
  tracking_number VARCHAR(150) NULL,
  courier_status VARCHAR(120) NULL,
  request_payload JSON NULL,
  response_payload JSON NULL,
  last_tracking_checked_at DATETIME NULL,
  created_by BIGINT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_waybill_source (source_type, source_order_id),
  KEY idx_waybill_id (waybill_id),
  KEY idx_tracking_number (tracking_number)
);

CREATE TABLE IF NOT EXISTS trans_express_tracking_events (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  waybill_id BIGINT UNSIGNED NOT NULL,
  tracking_status VARCHAR(120) NULL,
  tracking_description TEXT NULL,
  tracking_location VARCHAR(255) NULL,
  event_time DATETIME NULL,
  raw_payload JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_tracking_events_waybill (waybill_id),
  KEY idx_tracking_events_time (event_time)
);

CREATE TABLE IF NOT EXISTS packing_materials (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  material_code VARCHAR(100) NOT NULL,
  material_name VARCHAR(255) NOT NULL,
  material_type VARCHAR(120) NULL,
  unit VARCHAR(50) DEFAULT 'pcs',
  current_qty DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  reorder_level DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  unit_cost DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  supplier_name VARCHAR(255) NULL,
  status VARCHAR(30) DEFAULT 'ACTIVE',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_material_code (material_code)
);

CREATE TABLE IF NOT EXISTS packing_material_movements (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  material_id BIGINT UNSIGNED NOT NULL,
  movement_type VARCHAR(20) NOT NULL,
  qty DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  unit_cost DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  reference_type VARCHAR(100) NULL,
  reference_id VARCHAR(100) NULL,
  note TEXT NULL,
  created_by BIGINT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_packing_movement_material (material_id)
);

CREATE TABLE IF NOT EXISTS order_sync_settings (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  platform_code VARCHAR(50) NOT NULL,
  sync_enabled TINYINT(1) NOT NULL DEFAULT 1,
  auto_sync_enabled TINYINT(1) NOT NULL DEFAULT 1,
  sync_interval_minutes INT NOT NULL DEFAULT 5,
  fetch_order_days INT NOT NULL DEFAULT 7,
  last_sync_at DATETIME NULL,
  last_sync_started_at DATETIME NULL,
  last_sync_finished_at DATETIME NULL,
  last_sync_status VARCHAR(50) DEFAULT 'never',
  last_sync_message TEXT NULL,
  last_error_message TEXT NULL,
  next_sync_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_sync_platform (platform_code)
);


CREATE TABLE IF NOT EXISTS daraz_order_sync_runs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  account_id BIGINT NULL,
  account_code VARCHAR(100) NULL,
  account_name VARCHAR(255) NULL,
  sync_type VARCHAR(50) DEFAULT 'manual',
  days INT NULL,
  date_from DATE NULL,
  date_to DATE NULL,
  limit_rows INT NULL,
  max_pages INT NULL,
  status VARCHAR(50) DEFAULT 'running',
  fetched_orders INT NOT NULL DEFAULT 0,
  saved_orders INT NOT NULL DEFAULT 0,
  inserted_orders INT NOT NULL DEFAULT 0,
  updated_orders INT NOT NULL DEFAULT 0,
  skipped_orders INT NOT NULL DEFAULT 0,
  saved_items INT NOT NULL DEFAULT 0,
  confirmed_orders INT NOT NULL DEFAULT 0,
  error_message TEXT NULL,
  request_payload JSON NULL,
  response_payload JSON NULL,
  started_at DATETIME NULL,
  finished_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_daraz_sync_account (account_id),
  KEY idx_daraz_sync_status (status),
  KEY idx_daraz_sync_created (created_at)
);

CREATE TABLE IF NOT EXISTS woo_order_sync_runs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  account_id BIGINT NULL,
  account_code VARCHAR(100) NULL,
  account_name VARCHAR(255) NULL,
  sync_type VARCHAR(50) DEFAULT 'manual',
  days INT NULL,
  date_from DATE NULL,
  date_to DATE NULL,
  limit_rows INT NULL,
  max_pages INT NULL,
  status VARCHAR(50) DEFAULT 'running',
  fetched_orders INT NOT NULL DEFAULT 0,
  saved_orders INT NOT NULL DEFAULT 0,
  inserted_orders INT NOT NULL DEFAULT 0,
  updated_orders INT NOT NULL DEFAULT 0,
  skipped_orders INT NOT NULL DEFAULT 0,
  saved_items INT NOT NULL DEFAULT 0,
  confirmed_orders INT NOT NULL DEFAULT 0,
  error_message TEXT NULL,
  request_payload JSON NULL,
  response_payload JSON NULL,
  started_at DATETIME NULL,
  finished_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_woo_sync_account (account_id),
  KEY idx_woo_sync_status (status),
  KEY idx_woo_sync_created (created_at)
);

CREATE TABLE IF NOT EXISTS order_logs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  source_type VARCHAR(50) NULL,
  source_order_id BIGINT NULL,
  order_no VARCHAR(100) NULL,
  event_type VARCHAR(100) NULL,
  old_value TEXT NULL,
  new_value TEXT NULL,
  message TEXT NULL,
  raw_payload JSON NULL,
  created_by BIGINT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_order_logs_source (source_type, source_order_id),
  KEY idx_order_logs_created_at (created_at)
);

INSERT INTO order_sync_settings (platform_code, sync_enabled, auto_sync_enabled, sync_interval_minutes, fetch_order_days, last_sync_status)
VALUES
  ('DARAZ', 1, 1, 5, 7, 'never'),
  ('WOO', 1, 1, 5, 7, 'never'),
  ('TRANS_EXPRESS', 1, 1, 180, 7, 'never')
ON DUPLICATE KEY UPDATE platform_code = VALUES(platform_code);
